/**
 * @file system/get_limits.hpp
 * @brief API request: system/get_limits
 *
 * @copyright Copyright 2014 Mediafire
 *
 * This file was generated by gen_api_template.py. Do NOT edit by hand.
 */
#pragma once

#include "get_limits/v0.hpp"

namespace mf {
namespace api {
/** API action path "system" */
namespace system {
/** API action "system/get_limits" */
namespace get_limits {

// Default version
using namespace v0;  // NOLINT

}  // namespace get_limits
}  // namespace system
}  // namespace api
}  // namespace mf
