/**
 * @file system/get_version.hpp
 * @brief API request: system/get_version
 *
 * @copyright Copyright 2014 Mediafire
 *
 * This file was generated by gen_api_template.py. Do NOT edit by hand.
 */
#pragma once

#include "get_version/v0.hpp"

namespace mf {
namespace api {
/** API action path "system" */
namespace system {
/** API action "system/get_version" */
namespace get_version {

// Default version
using namespace v0;  // NOLINT

}  // namespace get_version
}  // namespace system
}  // namespace api
}  // namespace mf
