/**
 * @file notifications/get_cache.hpp
 * @brief API request: notifications/get_cache
 *
 * @copyright Copyright 2014 Mediafire
 *
 * This file was generated by gen_api_template.py. Do NOT edit by hand.
 */
#pragma once

#include "get_cache/v0.hpp"

namespace mf {
namespace api {
/** API action path "notifications" */
namespace notifications {
/** API action "notifications/get_cache" */
namespace get_cache {

// Default version
using namespace v0;  // NOLINT

}  // namespace get_cache
}  // namespace notifications
}  // namespace api
}  // namespace mf
