/**
 * @file api/notifications/peek_cache.hpp
 * @brief API request: /api/notifications/peek_cache
 *
 * @copyright Copyright 2014 Mediafire
 *
 * This file was generated by gen_api_template.py. Do NOT edit by hand.
 */
#pragma once

#include <string>
#include <vector>

#include "mediafire_sdk/http/shared_buffer.hpp"
#include "mediafire_sdk/http/headers.hpp"
#include "mediafire_sdk/api/response_base.hpp"

#include "boost/date_time/posix_time/ptime.hpp"

namespace mf {
namespace api {
/** API action path "notifications" */
namespace notifications {
/** API action "notifications/peek_cache" */
namespace peek_cache {
/** API path "/api/notifications/peek_cache" */
namespace v0 {

/**
 * @class Response
 * @brief Response from API request "notifications/peek_cache"
 */
class Response : public ResponseBase
{
public:
    /** API response field "response.num_total" */
    uint32_t total;

    /** API response field "response.num_unread" */
    uint32_t unread;

    /** API response field "response.last_timestamp" */
    uint64_t last_timestamp;
};

class Impl;

/**
 * @class Request
 * @brief Make API request "notifications/peek_cache"
 */
class Request
{
public:
    /**
     * API request "notifications/peek_cache"
     */
    Request();

    // Remaining functions are for use by API library only. --------------------

    /** Requester/SessionMaintainer expected type. */
    typedef Response ResponseType;

    /** Requester/SessionMaintainer expected type. */
    typedef std::function< void( const ResponseType & data)> CallbackType;

    /** Requester/SessionMaintainer expected type. */
    void SetCallback( CallbackType callback_function );

    /** Requester expected method. */
    void HandleContent(
            const std::string & url,
            const mf::http::Headers & headers,
            const std::string & content
        );

    /** Requester expected method. */
    void HandleError(
            const std::string & url,
            std::error_code ec,
            const std::string & error_string
        );

    /** Requester expected method. */
    std::string Url(const std::string & hostname) const;

    /** Requester optional method. */
    mf::http::SharedBuffer::Pointer GetPostData();

    /** SessionMaintainer expected method. */
    void SetSessionToken(
            std::string session_token,
            std::string time,
            int secret_key
        );
private:
    std::shared_ptr<Impl> impl_;
};
}  // namespace v0

// The latest version
using namespace v0;  // NOLINT

}  // namespace peek_cache
}  // namespace notifications
}  // namespace api
}  // namespace mf
