/**
 * @file notifications/peek_cache.hpp
 * @brief API request: notifications/peek_cache
 *
 * @copyright Copyright 2014 Mediafire
 *
 * This file was generated by gen_api_template.py. Do NOT edit by hand.
 */
#pragma once

#include "peek_cache/v0.hpp"

namespace mf {
namespace api {
/** API action path "notifications" */
namespace notifications {
/** API action "notifications/peek_cache" */
namespace peek_cache {

// Default version
using namespace v0;  // NOLINT

}  // namespace peek_cache
}  // namespace notifications
}  // namespace api
}  // namespace mf
