/**
 * @file billing/cancel_plan.hpp
 * @brief API request: billing/cancel_plan
 *
 * @copyright Copyright 2014 Mediafire
 *
 * This file was generated by gen_api_template.py. Do NOT edit by hand.
 */
#pragma once

#include "cancel_plan/v1_1.hpp"

namespace mf {
namespace api {
/** API action path "billing" */
namespace billing {
/** API action "billing/cancel_plan" */
namespace cancel_plan {

// Default version
using namespace v1_1;  // NOLINT

}  // namespace cancel_plan
}  // namespace billing
}  // namespace api
}  // namespace mf
