/**
 * @file billing/get_products.hpp
 * @brief API request: billing/get_products
 *
 * @copyright Copyright 2014 Mediafire
 *
 * This file was generated by gen_api_template.py. Do NOT edit by hand.
 */
#pragma once

#include "get_products/v1_1.hpp"

namespace mf {
namespace api {
/** API action path "billing" */
namespace billing {
/** API action "billing/get_products" */
namespace get_products {

// Default version
using namespace v1_1;  // NOLINT

}  // namespace get_products
}  // namespace billing
}  // namespace api
}  // namespace mf
