/**
 * @file api/device/get_status.hpp
 * @brief API request: /api/device/get_status
 *
 * @copyright Copyright 2014 Mediafire
 *
 * This file was generated by gen_api_template.py. Do NOT edit by hand.
 */
#pragma once

#include <string>
#include <vector>

#include "mediafire_sdk/http/shared_buffer.hpp"
#include "mediafire_sdk/http/headers.hpp"
#include "mediafire_sdk/api/response_base.hpp"

#include "boost/date_time/posix_time/ptime.hpp"

namespace mf {
namespace api {
/** API action path "device" */
namespace device {
/** API action "device/get_status" */
namespace get_status {
/** API path "/api/device/get_status" */
namespace v0 {

enum class AsyncJobs
{
    /** API value "no" */
    Stopped,
    /** API value "yes" */
    Running
};

/**
 * @class Response
 * @brief Response from API request "device/get_status"
 */
class Response : public ResponseBase
{
public:
    /** API response field "response.async_jobs_in_progress" */
    AsyncJobs async_jobs_in_progress;

    /** API response field "response.device_revision" */
    uint32_t device_revision;
};

class Impl;

/**
 * @class Request
 * @brief Make API request "device/get_status"
 */
class Request
{
public:
    /**
     * API request "device/get_status"
     */
    Request();

    /**
     * Optional API parameter "device_id"
     *
     * @param device_id Set parameter "device_id" in API request.
     */
    void SetDeviceId(uint32_t device_id);

    // Remaining functions are for use by API library only. --------------------

    /** Requester/SessionMaintainer expected type. */
    typedef Response ResponseType;

    /** Requester/SessionMaintainer expected type. */
    typedef std::function< void( const ResponseType & data)> CallbackType;

    /** Requester/SessionMaintainer expected type. */
    void SetCallback( CallbackType callback_function );

    /** Requester expected method. */
    void HandleContent(
            const std::string & url,
            const mf::http::Headers & headers,
            const std::string & content
        );

    /** Requester expected method. */
    void HandleError(
            const std::string & url,
            std::error_code ec,
            const std::string & error_string
        );

    /** Requester expected method. */
    std::string Url(const std::string & hostname) const;

    /** Requester optional method. */
    mf::http::SharedBuffer::Pointer GetPostData();

    /** SessionMaintainer expected method. */
    void SetSessionToken(
            std::string session_token,
            std::string time,
            int secret_key
        );
private:
    std::shared_ptr<Impl> impl_;
};
}  // namespace v0

}  // namespace get_status
}  // namespace device
}  // namespace api
}  // namespace mf
