/**
 * @file device/get_changes.hpp
 * @brief API request: device/get_changes
 *
 * @copyright Copyright 2014 Mediafire
 *
 * This file was generated by gen_api_template.py. Do NOT edit by hand.
 */
#pragma once

#include "get_changes/v0.hpp"
#include "get_changes/v1_3.hpp"

namespace mf {
namespace api {
/** API action path "device" */
namespace device {
/** API action "device/get_changes" */
namespace get_changes {

// Default version
using namespace v1_3;  // NOLINT

}  // namespace get_changes
}  // namespace device
}  // namespace api
}  // namespace mf
