/**
 * @file device/get_foreign_changes.hpp
 * @brief API request: device/get_foreign_changes
 *
 * @copyright Copyright 2014 Mediafire
 *
 * This file was generated by gen_api_template.py. Do NOT edit by hand.
 */
#pragma once

#include "get_foreign_changes/v0.hpp"

namespace mf {
namespace api {
/** API action path "device" */
namespace device {
/** API action "device/get_foreign_changes" */
namespace get_foreign_changes {

// Default version
using namespace v0;  // NOLINT

}  // namespace get_foreign_changes
}  // namespace device
}  // namespace api
}  // namespace mf
