/**
 * @file device/get_status.hpp
 * @brief API request: device/get_status
 *
 * @copyright Copyright 2014 Mediafire
 *
 * This file was generated by gen_api_template.py. Do NOT edit by hand.
 */
#pragma once

#include "get_status/v0.hpp"

namespace mf {
namespace api {
/** API action path "device" */
namespace device {
/** API action "device/get_status" */
namespace get_status {

// Default version
using namespace v0;  // NOLINT

}  // namespace get_status
}  // namespace device
}  // namespace api
}  // namespace mf
