/**
 * @file device/get_foreign_resources.hpp
 * @brief API request: device/get_foreign_resources
 *
 * @copyright Copyright 2014 Mediafire
 *
 * This file was generated by gen_api_template.py. Do NOT edit by hand.
 */
#pragma once

#include "get_foreign_resources/v0.hpp"

namespace mf {
namespace api {
/** API action path "device" */
namespace device {
/** API action "device/get_foreign_resources" */
namespace get_foreign_resources {

// Default version
using namespace v0;  // NOLINT

}  // namespace get_foreign_resources
}  // namespace device
}  // namespace api
}  // namespace mf
