/**
 * @file device/get_user_shares.hpp
 * @brief API request: device/get_user_shares
 *
 * @copyright Copyright 2014 Mediafire
 *
 * This file was generated by gen_api_template.py. Do NOT edit by hand.
 */
#pragma once

#include "get_user_shares/v0.hpp"

namespace mf {
namespace api {
/** API action path "device" */
namespace device {
/** API action "device/get_user_shares" */
namespace get_user_shares {

// Default version
using namespace v0;  // NOLINT

}  // namespace get_user_shares
}  // namespace device
}  // namespace api
}  // namespace mf
