/**
 * @file device/get_patch.hpp
 * @brief API request: device/get_patch
 *
 * @copyright Copyright 2014 Mediafire
 *
 * This file was generated by gen_api_template.py. Do NOT edit by hand.
 */
#pragma once

#include "get_patch/v0.hpp"

namespace mf {
namespace api {
/** API action path "device" */
namespace device {
/** API action "device/get_patch" */
namespace get_patch {

// Default version
using namespace v0;  // NOLINT

}  // namespace get_patch
}  // namespace device
}  // namespace api
}  // namespace mf
