/**
 * @file device/get_updates.hpp
 * @brief API request: device/get_updates
 *
 * @copyright Copyright 2014 Mediafire
 *
 * This file was generated by gen_api_template.py. Do NOT edit by hand.
 */
#pragma once

#include "get_updates/v0.hpp"

namespace mf {
namespace api {
/** API action path "device" */
namespace device {
/** API action "device/get_updates" */
namespace get_updates {

// Default version
using namespace v0;  // NOLINT

}  // namespace get_updates
}  // namespace device
}  // namespace api
}  // namespace mf
