/**
 * @file device/unshare_resource.hpp
 * @brief API request: device/unshare_resource
 *
 * @copyright Copyright 2014 Mediafire
 *
 * This file was generated by gen_api_template.py. Do NOT edit by hand.
 */
#pragma once

#include "unshare_resource/v0.hpp"

namespace mf {
namespace api {
/** API action path "device" */
namespace device {
/** API action "device/unshare_resource" */
namespace unshare_resource {

// Default version
using namespace v0;  // NOLINT

}  // namespace unshare_resource
}  // namespace device
}  // namespace api
}  // namespace mf
