/**
 * @file upload/add_web_upload.hpp
 * @brief API request: upload/add_web_upload
 *
 * @copyright Copyright 2014 Mediafire
 *
 * This file was generated by gen_api_template.py. Do NOT edit by hand.
 */
#pragma once

#include "add_web_upload/v1_3.hpp"

namespace mf {
namespace api {
/** API action path "upload" */
namespace upload {
/** API action "upload/add_web_upload" */
namespace add_web_upload {

// Default version
using namespace v1_3;  // NOLINT

}  // namespace add_web_upload
}  // namespace upload
}  // namespace api
}  // namespace mf
