/**
 * @file upload/check.hpp
 * @brief API request: upload/check
 *
 * @copyright Copyright 2014 Mediafire
 *
 * This file was generated by gen_api_template.py. Do NOT edit by hand.
 */
#pragma once

#include "check/v0.hpp"

namespace mf {
namespace api {
/** API action path "upload" */
namespace upload {
/** API action "upload/check" */
namespace check {

// Default version
using namespace v0;  // NOLINT

}  // namespace check
}  // namespace upload
}  // namespace api
}  // namespace mf
