/**
 * @file upload/get_web_uploads.hpp
 * @brief API request: upload/get_web_uploads
 *
 * @copyright Copyright 2014 Mediafire
 *
 * This file was generated by gen_api_template.py. Do NOT edit by hand.
 */
#pragma once

#include "get_web_uploads/v1_3.hpp"

namespace mf {
namespace api {
/** API action path "upload" */
namespace upload {
/** API action "upload/get_web_uploads" */
namespace get_web_uploads {

// Default version
using namespace v1_3;  // NOLINT

}  // namespace get_web_uploads
}  // namespace upload
}  // namespace api
}  // namespace mf
