/**
 * @file upload/instant.hpp
 * @brief API request: upload/instant
 *
 * @copyright Copyright 2014 Mediafire
 *
 * This file was generated by gen_api_template.py. Do NOT edit by hand.
 */
#pragma once

#include "instant/v0.hpp"

namespace mf {
namespace api {
/** API action path "upload" */
namespace upload {
/** API action "upload/instant" */
namespace instant {

// Default version
using namespace v0;  // NOLINT

}  // namespace instant
}  // namespace upload
}  // namespace api
}  // namespace mf
