/**
 * @file upload/pre_upload.hpp
 * @brief API request: upload/pre_upload
 *
 * @copyright Copyright 2014 Mediafire
 *
 * This file was generated by gen_api_template.py. Do NOT edit by hand.
 */
#pragma once

#include "pre_upload/v0.hpp"

namespace mf {
namespace api {
/** API action path "upload" */
namespace upload {
/** API action "upload/pre_upload" */
namespace pre_upload {

// Default version
using namespace v0;  // NOLINT

}  // namespace pre_upload
}  // namespace upload
}  // namespace api
}  // namespace mf
