/**
 * @file api/folder/update.hpp
 * @brief API request: /api/folder/update
 *
 * @copyright Copyright 2014 Mediafire
 *
 * This file was generated by gen_api_template.py. Do NOT edit by hand.
 */
#pragma once

#include <string>
#include <vector>

#include "mediafire_sdk/http/shared_buffer.hpp"
#include "mediafire_sdk/http/headers.hpp"
#include "mediafire_sdk/api/response_base.hpp"

#include "boost/date_time/posix_time/ptime.hpp"

namespace mf {
namespace api {
/** API action path "folder" */
namespace folder {
/** API action "folder/update" */
namespace update {
/** API path "/api/folder/update" */
namespace v0 {

enum class Asynchronous
{
    /** API value "no" */
    Synchronous,
    /** API value "yes" */
    Asynchronous
};

enum class Privacy
{
    /** API value "public" */
    Public,
    /** API value "private" */
    Private
};

enum class PrivacyRecursive
{
    /** API value "no" */
    NonRecursive,
    /** API value "yes" */
    Recursive
};

/**
 * @class Response
 * @brief Response from API request "folder/update"
 */
class Response : public ResponseBase
{
public:
    Response() :
        asynchronous(Asynchronous::Synchronous)
    {}
    /** API response field "response.asynchronous" */
    Asynchronous asynchronous;

    /** API response field "response.device_revision" */
    boost::optional<uint32_t> device_revision;
};

class Impl;

/**
 * @class Request
 * @brief Make API request "folder/update"
 */
class Request
{
public:
    /**
     * API request "folder/update"
     *
     * @param folderkey API parameter "folder_key"
     */
    explicit Request(
            std::string folderkey
        );

    /**
     * Optional API parameter "foldername"
     *
     * @param foldername Set parameter "foldername" in API request.
     */
    void SetFoldername(std::string foldername);

    /**
     * Optional API parameter "description"
     *
     * @param description Set parameter "description" in API request.
     */
    void SetDescription(std::string description);

    /**
     * Optional API parameter "privacy"
     *
     * @param privacy Set parameter "privacy" in API request.
     */
    void SetPrivacy(Privacy privacy);

    /**
     * Optional API parameter "privacy_recursive"
     *
     * @param privacy_recursive Set parameter "privacy_recursive" in API
     *                          request.
     */
    void SetPrivacyRecursive(PrivacyRecursive privacy_recursive);

    /**
     * Optional API parameter "mtime"
     *
     * @param mtime Set parameter "mtime" in API request.
     */
    void SetMtime(boost::posix_time::ptime mtime);

    // Remaining functions are for use by API library only. --------------------

    /** Requester/SessionMaintainer expected type. */
    typedef Response ResponseType;

    /** Requester/SessionMaintainer expected type. */
    typedef std::function< void( const ResponseType & data)> CallbackType;

    /** Requester/SessionMaintainer expected type. */
    void SetCallback( CallbackType callback_function );

    /** Requester expected method. */
    void HandleContent(
            const std::string & url,
            const mf::http::Headers & headers,
            const std::string & content
        );

    /** Requester expected method. */
    void HandleError(
            const std::string & url,
            std::error_code ec,
            const std::string & error_string
        );

    /** Requester expected method. */
    std::string Url(const std::string & hostname) const;

    /** Requester optional method. */
    mf::http::SharedBuffer::Pointer GetPostData();

    /** SessionMaintainer expected method. */
    void SetSessionToken(
            std::string session_token,
            std::string time,
            int secret_key
        );

    // Enums in class namespace for usage with templates
    using Asynchronous = enum Asynchronous;
    using Privacy = enum Privacy;
    using PrivacyRecursive = enum PrivacyRecursive;

private:
    std::shared_ptr<Impl> impl_;
};
}  // namespace v0

}  // namespace update
}  // namespace folder
}  // namespace api
}  // namespace mf
