/**
 * @file contact/fetch.hpp
 * @brief API request: contact/fetch
 *
 * @copyright Copyright 2014 Mediafire
 *
 * This file was generated by gen_api_template.py. Do NOT edit by hand.
 */
#pragma once

#include "fetch/v0.hpp"

namespace mf {
namespace api {
/** API action path "contact" */
namespace contact {
/** API action "contact/fetch" */
namespace fetch {

// Default version
using namespace v0;  // NOLINT

}  // namespace fetch
}  // namespace contact
}  // namespace api
}  // namespace mf
