/**
 * @file file/copy.hpp
 * @brief API request: file/copy
 *
 * @copyright Copyright 2014 Mediafire
 *
 * This file was generated by gen_api_template.py. Do NOT edit by hand.
 */
#pragma once

#include "copy/v0.hpp"
#include "copy/v1_3.hpp"

namespace mf {
namespace api {
/** API action path "file" */
namespace file {
/** API action "file/copy" */
namespace copy {

// Default version
using namespace v1_3;  // NOLINT

}  // namespace copy
}  // namespace file
}  // namespace api
}  // namespace mf
