/**
 * @file file/create.hpp
 * @brief API request: file/create
 *
 * @copyright Copyright 2014 Mediafire
 *
 * This file was generated by gen_api_template.py. Do NOT edit by hand.
 */
#pragma once

#include "create/v0.hpp"
#include "create/v1_2.hpp"
#include "create/v1_3.hpp"

namespace mf {
namespace api {
/** API action path "file" */
namespace file {
/** API action "file/create" */
namespace create {

// Default version
using namespace v1_3;  // NOLINT

}  // namespace create
}  // namespace file
}  // namespace api
}  // namespace mf
