/**
 * @file file/file_delete.hpp
 * @brief API request: file/file_delete
 *
 * @copyright Copyright 2014 Mediafire
 *
 * This file was generated by gen_api_template.py. Do NOT edit by hand.
 */
#pragma once

#include "file_delete/v0.hpp"

namespace mf {
namespace api {
/** API action path "file" */
namespace file {
/** API action "file/file_delete" */
namespace file_delete {

// Default version
using namespace v0;  // NOLINT

}  // namespace file_delete
}  // namespace file
}  // namespace api
}  // namespace mf
