/**
 * @file file/get_info.hpp
 * @brief API request: file/get_info
 *
 * @copyright Copyright 2014 Mediafire
 *
 * This file was generated by gen_api_template.py. Do NOT edit by hand.
 */
#pragma once

#include "get_info/v0.hpp"

namespace mf {
namespace api {
/** API action path "file" */
namespace file {
/** API action "file/get_info" */
namespace get_info {

// Default version
using namespace v0;  // NOLINT

}  // namespace get_info
}  // namespace file
}  // namespace api
}  // namespace mf
