/**
 * @file file/move.hpp
 * @brief API request: file/move
 *
 * @copyright Copyright 2014 Mediafire
 *
 * This file was generated by gen_api_template.py. Do NOT edit by hand.
 */
#pragma once

#include "move/v0.hpp"

namespace mf {
namespace api {
/** API action path "file" */
namespace file {
/** API action "file/move" */
namespace move {

// Default version
using namespace v0;  // NOLINT

}  // namespace move
}  // namespace file
}  // namespace api
}  // namespace mf
