/**
 * @file file/one_time_key.hpp
 * @brief API request: file/one_time_key
 *
 * @copyright Copyright 2014 Mediafire
 *
 * This file was generated by gen_api_template.py. Do NOT edit by hand.
 */
#pragma once

#include "one_time_key/v1_1.hpp"
#include "one_time_key/v1_3.hpp"

namespace mf {
namespace api {
/** API action path "file" */
namespace file {
/** API action "file/one_time_key" */
namespace one_time_key {

// Default version
using namespace v1_3;  // NOLINT

}  // namespace one_time_key
}  // namespace file
}  // namespace api
}  // namespace mf
