/**
 * @file file/purge.hpp
 * @brief API request: file/purge
 *
 * @copyright Copyright 2014 Mediafire
 *
 * This file was generated by gen_api_template.py. Do NOT edit by hand.
 */
#pragma once

#include "purge/v0.hpp"

namespace mf {
namespace api {
/** API action path "file" */
namespace file {
/** API action "file/purge" */
namespace purge {

// Default version
using namespace v0;  // NOLINT

}  // namespace purge
}  // namespace file
}  // namespace api
}  // namespace mf
