/**
 * @file file/recently_modified.hpp
 * @brief API request: file/recently_modified
 *
 * @copyright Copyright 2014 Mediafire
 *
 * This file was generated by gen_api_template.py. Do NOT edit by hand.
 */
#pragma once

#include "recently_modified/v0.hpp"

namespace mf {
namespace api {
/** API action path "file" */
namespace file {
/** API action "file/recently_modified" */
namespace recently_modified {

// Default version
using namespace v0;  // NOLINT

}  // namespace recently_modified
}  // namespace file
}  // namespace api
}  // namespace mf
