/**
 * @file file/update_file.hpp
 * @brief API request: file/update_file
 *
 * @copyright Copyright 2014 Mediafire
 *
 * This file was generated by gen_api_template.py. Do NOT edit by hand.
 */
#pragma once

#include "update_file/v0.hpp"

namespace mf {
namespace api {
/** API action path "file" */
namespace file {
/** API action "file/update_file" */
namespace update_file {

// Default version
using namespace v0;  // NOLINT

}  // namespace update_file
}  // namespace file
}  // namespace api
}  // namespace mf
