/**
 * @file user/fetch_tos.hpp
 * @brief API request: user/fetch_tos
 *
 * @copyright Copyright 2014 Mediafire
 *
 * This file was generated by gen_api_template.py. Do NOT edit by hand.
 */
#pragma once

#include "fetch_tos/v1_3.hpp"

namespace mf {
namespace api {
/** API action path "user" */
namespace user {
/** API action "user/fetch_tos" */
namespace fetch_tos {

// Default version
using namespace v1_3;  // NOLINT

}  // namespace fetch_tos
}  // namespace user
}  // namespace api
}  // namespace mf
