/**
 * @file user/get_action_token.hpp
 * @brief API request: user/get_action_token
 *
 * @copyright Copyright 2014 Mediafire
 *
 * This file was generated by gen_api_template.py. Do NOT edit by hand.
 */
#pragma once

#include "get_action_token/v1_0.hpp"
#include "get_action_token/v1_3.hpp"

namespace mf {
namespace api {
/** API action path "user" */
namespace user {
/** API action "user/get_action_token" */
namespace get_action_token {

// Default version
using namespace v1_3;  // NOLINT

}  // namespace get_action_token
}  // namespace user
}  // namespace api
}  // namespace mf
