/**
 * @file user/get_settings.hpp
 * @brief API request: user/get_settings
 *
 * @copyright Copyright 2014 Mediafire
 *
 * This file was generated by gen_api_template.py. Do NOT edit by hand.
 */
#pragma once

#include "get_settings/v1_3.hpp"

namespace mf {
namespace api {
/** API action path "user" */
namespace user {
/** API action "user/get_settings" */
namespace get_settings {

// Default version
using namespace v1_3;  // NOLINT

}  // namespace get_settings
}  // namespace user
}  // namespace api
}  // namespace mf
