/**
 * @file user/get_limits.hpp
 * @brief API request: user/get_limits
 *
 * @copyright Copyright 2014 Mediafire
 *
 * This file was generated by gen_api_template.py. Do NOT edit by hand.
 */
#pragma once

#include "get_limits/v0.hpp"
#include "get_limits/v1_3.hpp"

namespace mf {
namespace api {
/** API action path "user" */
namespace user {
/** API action "user/get_limits" */
namespace get_limits {

// Default version
using namespace v1_3;  // NOLINT

}  // namespace get_limits
}  // namespace user
}  // namespace api
}  // namespace mf
