/**
 * @file user/link_twitter.hpp
 * @brief API request: user/link_twitter
 *
 * @copyright Copyright 2014 Mediafire
 *
 * This file was generated by gen_api_template.py. Do NOT edit by hand.
 */
#pragma once

#include "link_twitter/v0.hpp"

namespace mf {
namespace api {
/** API action path "user" */
namespace user {
/** API action "user/link_twitter" */
namespace link_twitter {

// Default version
using namespace v0;  // NOLINT

}  // namespace link_twitter
}  // namespace user
}  // namespace api
}  // namespace mf
