/**
 * @file user/set_avatar.hpp
 * @brief API request: user/set_avatar
 *
 * @copyright Copyright 2014 Mediafire
 *
 * This file was generated by gen_api_template.py. Do NOT edit by hand.
 */
#pragma once

#include "set_avatar/v1_3.hpp"

namespace mf {
namespace api {
/** API action path "user" */
namespace user {
/** API action "user/set_avatar" */
namespace set_avatar {

// Default version
using namespace v1_3;  // NOLINT

}  // namespace set_avatar
}  // namespace user
}  // namespace api
}  // namespace mf
