/**
 * @file user/unlink_twitter.hpp
 * @brief API request: user/unlink_twitter
 *
 * @copyright Copyright 2014 Mediafire
 *
 * This file was generated by gen_api_template.py. Do NOT edit by hand.
 */
#pragma once

#include "unlink_twitter/v0.hpp"
#include "unlink_twitter/v1_3.hpp"

namespace mf {
namespace api {
/** API action path "user" */
namespace user {
/** API action "user/unlink_twitter" */
namespace unlink_twitter {

// Default version
using namespace v1_3;  // NOLINT

}  // namespace unlink_twitter
}  // namespace user
}  // namespace api
}  // namespace mf
