/**
 * @file user/user_register.hpp
 * @brief API request: user/user_register
 *
 * @copyright Copyright 2014 Mediafire
 *
 * This file was generated by gen_api_template.py. Do NOT edit by hand.
 */
#pragma once

#include "user_register/v0.hpp"

namespace mf {
namespace api {
/** API action path "user" */
namespace user {
/** API action "user/user_register" */
namespace user_register {

// Default version
using namespace v0;  // NOLINT

}  // namespace user_register
}  // namespace user
}  // namespace api
}  // namespace mf
