/**
 * @file api/system/get_supported_media.hpp
 * @brief API request: /api/system/get_supported_media
 *
 * @copyright Copyright 2014 Mediafire
 *
 * This file was generated by gen_api_template.py. Do NOT edit by hand.
 */
#pragma once

#include <string>
#include <vector>

#include "mediafire_sdk/http/shared_buffer.hpp"
#include "mediafire_sdk/http/headers.hpp"
#include "mediafire_sdk/api/response_base.hpp"

#include "boost/date_time/posix_time/ptime.hpp"

namespace mf {
namespace api {
/** API action path "system" */
namespace system {
/** API action "system/get_supported_media" */
namespace get_supported_media {
/** API path "/api/system/get_supported_media" */
namespace v0 {

/**
 * @class Response
 * @brief Response from API request "system/get_supported_media"
 */
class Response : public ResponseBase
{
public:
    /** API response field "response.viewable.extensions" */
    std::vector<std::string> viewable_extensions;
};

class Impl;

/**
 * @class Request
 * @brief Make API request "system/get_supported_media"
 */
class Request
{
public:
    /**
     * API request "system/get_supported_media"
     */
    Request();

    // Remaining functions are for use by API library only. --------------------

    /** Requester/SessionMaintainer expected type. */
    typedef Response ResponseType;

    /** Requester/SessionMaintainer expected type. */
    typedef std::function< void( const ResponseType & data)> CallbackType;

    /** Requester/SessionMaintainer expected type. */
    void SetCallback( CallbackType callback_function );

    /** Requester expected method. */
    void HandleContent(
            const std::string & url,
            const mf::http::Headers & headers,
            const std::string & content
        );

    /** Requester expected method. */
    void HandleError(
            const std::string & url,
            std::error_code ec,
            const std::string & error_string
        );

    /** Requester expected method. */
    std::string Url(const std::string & hostname) const;

    /** Requester optional method. */
    mf::http::SharedBuffer::Pointer GetPostData();

    /** SessionMaintainer expected method. */
    void SetSessionToken(
            std::string session_token,
            std::string time,
            int secret_key
        );
private:
    std::shared_ptr<Impl> impl_;
};
}  // namespace v0

}  // namespace get_supported_media
}  // namespace system
}  // namespace api
}  // namespace mf
