/**
 * @file api/user/get_limits.hpp
 * @brief API request: /api/1.3/user/get_limits
 *
 * @copyright Copyright 2014 Mediafire
 *
 * This file was generated by gen_api_template.py. Do NOT edit by hand.
 */
#pragma once

#include <string>
#include <vector>

#include "mediafire_sdk/http/shared_buffer.hpp"
#include "mediafire_sdk/http/headers.hpp"
#include "mediafire_sdk/api/response_base.hpp"

#include "boost/date_time/posix_time/ptime.hpp"

namespace mf {
namespace api {
/** API action path "user" */
namespace user {
/** API action "user/get_limits" */
namespace get_limits {
/** API path "/api/1.3/user/get_limits" */
namespace v1_3 {

/**
 * @class Response
 * @brief Response from API request "user/get_limits"
 */
class Response : public ResponseBase
{
public:
    Response() :
        storage_base(0),
        storage_bonus(0),
        storage_limit(0),
        storage_used(0),
        bandwidth_limit(0),
        bandwidth_used(0),
        collaboration_limit(0),
        collaboration_today(0),
        one_time_downloads_limit(0),
        one_time_downloads_today(0),
        streaming_bandwidth_limit(0),
        streaming_bandwidth_today(0),
        upload_size_limit(0)
    {}
    /** API response field "response.storage_base" */
    uint64_t storage_base;

    /** API response field "response.storage_bonus" */
    uint64_t storage_bonus;

    /** API response field "response.storage_limit" */
    uint64_t storage_limit;

    /** API response field "response.storage_used" */
    uint64_t storage_used;

    /** API response field "response.bandwidth_limit" */
    uint64_t bandwidth_limit;

    /** API response field "response.bandwidth_used" */
    uint64_t bandwidth_used;

    /** API response field "response.collaboration_limit" */
    uint64_t collaboration_limit;

    /** API response field "response.collaboration_today" */
    uint64_t collaboration_today;

    /** API response field "response.one_time_downloads_limit" */
    uint64_t one_time_downloads_limit;

    /** API response field "response.one_time_downloads_today" */
    uint64_t one_time_downloads_today;

    /** API response field "response.streaming_bandwidth_limit" */
    uint64_t streaming_bandwidth_limit;

    /** API response field "response.streaming_bandwidth_today" */
    uint64_t streaming_bandwidth_today;

    /** API response field "response.upload_size_limit" */
    uint64_t upload_size_limit;
};

class Impl;

/**
 * @class Request
 * @brief Make API request "user/get_limits"
 */
class Request
{
public:
    /**
     * API request "user/get_limits"
     */
    Request();

    // Remaining functions are for use by API library only. --------------------

    /** Requester/SessionMaintainer expected type. */
    typedef Response ResponseType;

    /** Requester/SessionMaintainer expected type. */
    typedef std::function< void( const ResponseType & data)> CallbackType;

    /** Requester/SessionMaintainer expected type. */
    void SetCallback( CallbackType callback_function );

    /** Requester expected method. */
    void HandleContent(
            const std::string & url,
            const mf::http::Headers & headers,
            const std::string & content
        );

    /** Requester expected method. */
    void HandleError(
            const std::string & url,
            std::error_code ec,
            const std::string & error_string
        );

    /** Requester expected method. */
    std::string Url(const std::string & hostname) const;

    /** Requester optional method. */
    mf::http::SharedBuffer::Pointer GetPostData();

    /** SessionMaintainer expected method. */
    void SetSessionToken(
            std::string session_token,
            std::string time,
            int secret_key
        );
private:
    std::shared_ptr<Impl> impl_;
};
}  // namespace v1_3

}  // namespace get_limits
}  // namespace user
}  // namespace api
}  // namespace mf
