/**
 * @file folder/create.hpp
 * @brief API request: folder/create
 *
 * @copyright Copyright 2014 Mediafire
 *
 * This file was generated by gen_api_template.py. Do NOT edit by hand.
 */
#pragma once

#include "create/v0.hpp"

namespace mf {
namespace api {
/** API action path "folder" */
namespace folder {
/** API action "folder/create" */
namespace create {

// Default version
using namespace v0;  // NOLINT

}  // namespace create
}  // namespace folder
}  // namespace api
}  // namespace mf
