/**
 * @file folder/folder_delete.hpp
 * @brief API request: folder/folder_delete
 *
 * @copyright Copyright 2014 Mediafire
 *
 * This file was generated by gen_api_template.py. Do NOT edit by hand.
 */
#pragma once

#include "folder_delete/v0.hpp"

namespace mf {
namespace api {
/** API action path "folder" */
namespace folder {
/** API action "folder/folder_delete" */
namespace folder_delete {

// Default version
using namespace v0;  // NOLINT

}  // namespace folder_delete
}  // namespace folder
}  // namespace api
}  // namespace mf
